ssh-dev-germany-instance:
	ssh -i ./keys/prod-germany-instance-key.pem

ssh-dev-france-instance:
	ssh -i ./keys/dev-france-instance-key.pem

ssh-staging-germany-instance:
	ssh -i ./keys/staging-germany-instance-key.pem

ssh-staging-france-instance:
	ssh -i ./keys/staging-france-instance-key.pem

ssh-prod-france-instance:
	ssh -i ./keys/prod-france-instance-key.pem

ssh-prod-germany-instance:
	ssh -i ./keys/dev-germany-instance-key.pem
