version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env

  database:
    image: postgres:16
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - psql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 2s
      timeout: 1s
      retries: 10

  db-test:
    image: postgres:16
    container_name: porsche_db_test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=porsche_test
    ports:
      - "5433:5432"  # Port différent pour la base de test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  psql-data:
  postgres_test_data:
